/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import AtlasAniView from "./View/AtlasAniView"
import BackpackView from "./View/BackpackView"
import ProgressBarView from "./View/ProgressBarView"
import ColorFilterView from "./View/ColorFilterView"
import MyColorFilter from "./ColorFilter/MyColorFilter"
import ComboBoxView from "./View/ComboBoxView"
import DlgShowView from "./View/DlgShowView"
import FontNumView from "./View/FontNumView"
import FrameInfoView from "./View/FrameInfoView"
import HorselampView from "./View/HorselampView"
import HttpRequestView from "./View/HttpRequestView"
import Joystick3DCtrlView from "./View/Joystick3DCtrlView"
import JoystickView from "./View/JoystickView"
import MainView from "./View/MainView"
import ParticleView from "./View/ParticleView"
import PrefabAniView from "./View/PrefabAniView"
import RadioView from "./View/RadioView"
import RayCastToMoveView from "./View/RayCastToMoveView"
import Scene3DView from "./View/Scene3DView"
import SoundPlayView from "./View/SoundPlayView"
import TabPageView from "./View/TabPageView"
import TextTipsView from "./View/TextTipsView"
import TimeCountView from "./View/TimeCountView"
import WebHeadView from "./View/WebHeadView"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=640;
    static height:number=2048;
    static scaleMode:string="fixedwidth";
    static screenMode:string="none";
    static alignV:string="top";
    static alignH:string="left";
    static startScene:any="MainView.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=false;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("View/AtlasAniView.ts",AtlasAniView);
        reg("View/BackpackView.ts",BackpackView);
        reg("View/ProgressBarView.ts",ProgressBarView);
        reg("View/ColorFilterView.ts",ColorFilterView);
        reg("ColorFilter/MyColorFilter.ts",MyColorFilter);
        reg("View/ComboBoxView.ts",ComboBoxView);
        reg("View/DlgShowView.ts",DlgShowView);
        reg("View/FontNumView.ts",FontNumView);
        reg("View/FrameInfoView.ts",FrameInfoView);
        reg("View/HorselampView.ts",HorselampView);
        reg("View/HttpRequestView.ts",HttpRequestView);
        reg("View/Joystick3DCtrlView.ts",Joystick3DCtrlView);
        reg("View/JoystickView.ts",JoystickView);
        reg("View/MainView.ts",MainView);
        reg("View/ParticleView.ts",ParticleView);
        reg("View/PrefabAniView.ts",PrefabAniView);
        reg("View/RadioView.ts",RadioView);
        reg("View/RayCastToMoveView.ts",RayCastToMoveView);
        reg("View/Scene3DView.ts",Scene3DView);
        reg("View/SoundPlayView.ts",SoundPlayView);
        reg("View/TabPageView.ts",TabPageView);
        reg("View/TextTipsView.ts",TextTipsView);
        reg("View/TimeCountView.ts",TimeCountView);
        reg("View/WebHeadView.ts",WebHeadView);
    }
}
GameConfig.init();